language: rust
sudo: false
cache: cargo

git:
  depth: 1

env:
  - ARCH=x86_64
  - ARCH=i686

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly


before_install:
  - sudo apt-get update
  - cargo install cargo-bloat --force

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bloat --release --crates
  - cargo bloat --release -n 10
