language: rust
sudo: false
cache: cargo

git:
  depth: 5

env:
  - ARCH=x86_64
  - ARCH=i686

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_install:
  - sudo apt-get update
script:
  - cargo build --verbose
  - cargo test --verbose
