[package]
name = "gm8emu"
version = "0.1.0"
authors = ["viri <not.viri@protonmail.ch>"]
edition = "2018"

[dependencies]
getopts = "0.2.21"
gm8x = { git = "https://github.com/notviri/gm8x" }
winit = "0.20.0-alpha3"
