[package]
name = "gm8emu"
version = "0.1.0"
authors = ["viri <git@stuff.moe>"]
edition = "2018"

[build-dependencies]
gl_generator = "0.14.0"

[dependencies]
gl = "0.13.0"
gl_loader = "0.1.2"
glutin = "0.22.0-alpha2"
getopts = "0.2.21"
gm8x = { path = "lib/gm8x" }
rect_packer = "0.2.1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[workspace]
members = [ "lib/gm8x" ]
