[package]
name = "gm8emu"
version = "0.1.0"
authors = ["viri <git@stuff.moe>"]
edition = "2018"

[build-dependencies]
gl_generator = "0.14.0"

[dependencies]
glutin = "0.22.0-alpha2"
getopts = "0.2.21"
gm8x = { path = "lib/gm8x" }
rect_packer = "0.2.1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[workspace]
members = [
    "lib/gl",
    "lib/gm8x",
]
