[package]
name = "gm8emu"
version = "0.1.0"
authors = ["viri <not.viri@protonmail.ch>"]
edition = "2018"

[dependencies]
gm8x = { git = "https://github.com/notviri/gm8x" }

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
