[package]
name = "gm8emu"
version = "0.1.0"
authors = ["viri <git@stuff.moe>"]
edition = "2018"

[dependencies]
getopts = "0.2.21"
gm8x = { path = "lib/gm8x" }
winit = "0.20.0-alpha3"

[workspace]
members = [ "lib/gm8x" ]
