[package]
name = "gm8emulator"
version = "0.1.0"
authors = ["Adamcake", "viri"]
license = "GPL-2.0-only"
edition = "2018"

[build-dependencies]
gl_generator = "0.14.0"

[dependencies]
gl = { path = "lib/gl" }
glutin = "0.22.0-alpha2"
getopts = "0.2.21"
gm8exe = { git = "https://github.com/OpenGM8/GM8Decompiler.git" }
rect_packer = "0.2.1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[workspace]
members = ["lib/gl"]
