[package]
name = "gm8emu"
version = "0.1.0"
authors = ["viri <git@stuff.moe>"]
edition = "2018"

[dependencies]
gl = { path = "lib/gl" }
glutin = "0.22.0-alpha2"
getopts = "0.2.21"
gm8exe = { git = "https://github.com/OpenGM8/GM8Decompiler.git" }
rect_packer = "0.2.1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[workspace]
members = ["lib/gl"]
